{% set name = "mir-flare" %}
{% set version = "0.2.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mir-group/flare/archive/refs/tags/{{ version }}.tar.gz
  sha256: 21cebd3f5f65572b651cd599ef4c8fd6287bb2e6b2bbe80d211427f14803a8d9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
  host:
    - python
    - pip
  run:
    - python
    - numpy
    - scipy
    - memory_profiler
    - numba
    - ase

test:
  imports:
    - flare 
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/mir-group/flare
  summary: 'An open-source Python package for creating fast and accurate interatomic potentials.'
  description: |
    An open-source Python package for creating fast and accurate interatomic potentials.
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  doc_url: https://mir-group.github.io/flare
  dev_url: https://github.com/mir-group/flare

extra:
  recipe-maintainers:
    - YuuuXie 
